update autobuild

diff --git a/web/autobuild b/web/autobuild
--- a/web/autobuild
+++ b/web/autobuild
@@ -11,27 +11,25 @@ if ! npm install; then
   exit 1
 fi
 
-printf "cd to public dir...\n"
-
-if ! cd /var/www/html/theunderempire.com/public_html/dev/foodofthegods-react; then
-  printf "\ncd failed, are you on the server?\n"
+printf '\nrunning build...\n'
+if ! npm run --silent build; then
+  printf '\nthere was an error while building\n'
   exit 1
 fi
 
-printf '\nrunning build...\n'
-if npm run --silent build; then
-    printf '\nbuild completed!\n'
-    else printf '\nthere was an error while building\n'
-fi
+printf '\nbuild completed!\n'
+
+DEPLOY_DIR="/var/www/html/theunderempire.com/public_html/foodofthegods"
 
 printf '\nremoving old build\n'
-if ! rm -rf ../../foodofthegods/*; then
+if ! rm -rf "$DEPLOY_DIR"/*; then
   printf "\nrm of old site files failed\n"
   exit 1
 fi
 
 printf '\ndeploying new build...\n'
-if mv ./dist/* ../../foodofthegods/ && rm -rf ./dist && cp .htaccess ../../foodofthegods/.htaccess; then
-    printf '\ndeploy completed!\n'
-    else printf '\nthere was an error while deploying\n'
+if mv ./dist/* "$DEPLOY_DIR"/ && rm -rf ./dist && cp .htaccess "$DEPLOY_DIR"/.htaccess; then
+  printf '\ndeploy completed!\n'
+else
+  printf '\nthere was an error while deploying\n'
 fi
